### ISSUE TITLE
The named service networking is not available

### ISSUE THREAD

**Issue by immonju1** [jisosomppi/log-analysis#1]
After running server installation, networking service is failed

----------
          ID: networking
    Function: service.running
      Result: False
     Comment: The named service networking is not available
     Started: 10:42:29.597023
    Duration: 10.751 ms
     Changes: 

This becomes also after 
$ sudo salt '*' state.highstate --state-output terse

**Comment by sampohautala** [comment]
I also had this same issue:

This part failed, when running sudo salt 'srv*' state.highstate from master.

----------
          ID: networking
    Function: service.running
      Result: False
     Comment: The named service networking is not available
     Started: 10:55:21.770776
    Duration: 10.739 ms
     Changes:

**Comment by jisosomppi** [comment]
This issue has been fixed: the service networking is no longer available in Ubuntu versions after 16.04.
Restarting the service proved to be unnecessary, and was removed altogether.
