### ISSUE TITLE
Failed service.running

### ISSUE THREAD

**Issue by JoonasPit** [jisosomppi/log-analysis#11]
Not sure if I should be worried. But after running

- ./serversetup.sh

After the installation finishes I receive the error message:

- Name: networking - Function: service.running - Result: Failed Started: - 10:52:59.139304 Duration:  32.92 ms

Everything works fine otherwise so I think this isn't a serious issue. But I'd find it helpful if there was something telling the user that the failure isn't critical.

Also all the previous steps were completed. So the issue isn't about missing files.

**Comment by jisosomppi** [comment]
[This issue was fixed previously](https://github.com/jisosomppi/log-analysis/commit/c93897df62bf08fac2f8b61fd8d5625e5e6caff0), please update your files and retry (`rm -rf ~/log-analysis/`).
