### ISSUE TITLE
Master security enhancement

### ISSUE THREAD

**Issue by immonju1** [jisosomppi/log-analysis#13]
I didn't see any Firewall setup for Master server.                    
 
Centralized logs might require good security.

**Comment by jisosomppi** [comment]
Adding firewall rules (UFW) will be part of the final setup. Since it is as easy as changing one file with Salt, we have spent our time on more complex parts of the setup.

**Comment by nauskis** [comment]
https://github.com/jisosomppi/log-analysis/tree/master/salt/srvsalt/ufw  
Firewall setup has been added to the salt configuration.
