### ISSUE TITLE
Enhancement to the notes

### ISSUE THREAD

**Issue by sampohautala** [jisosomppi/log-analysis#2]
The info for this part should have a path to where the creation of the new index is found, for example like commented in the right spot:

The logging frontend is Kibana, which is automatically set up and started on the master.
The interface can be accessed either locally on the server (http://localhost) or from any salt minion (http://logserver.local). Kibana requires minimal setup after the initial scripts:

        **Add: Go to Discover-page found on the left side-bar.**
        Create new index (the easiest index pattern for this is " * "), choose @timestamp as the time filter
        Go to the Discover tab to see log entries

**Comment by jisosomppi** [comment]
Added to documentation.
