### ISSUE TITLE
Index pattern issue

### ISSUE THREAD

**Issue by KonstantinGurin** [jisosomppi/log-analysis#5]
Kaytin Ubuntu 18.04.1 LTS.
Koneeseen on asennettu pelkaan salt-master. eli ./serversetup.sh
Tuli vastaan virhe, etta en pystynyt luoda uuden index patternin.
![screenshot from 2018-11-13 12-39-39](https://user-images.githubusercontent.com/43230138/48413973-3ef60080-e741-11e8-842c-481ae711e7e7.png)

T: Konstantin Gurin

**Comment by jisosomppi** [comment]
Uutta index patternia ei voi luoda, jos Elasticsearchissa ei ole vielä mitään dataa. Kannattaa siis tehdä clientin asennus, luoda sen kautta testidataa ja yrittää uudelleen. Automaattinen testidatan lisäys tulossa tulevaan versioon.

**Comment by KonstantinGurin** [comment]
Ratkaistu! Se oli vaan joku bugi. Komento: **logger -s testmessage** ei generoinut log data jostain syysta.
