### ISSUE TITLE
How do I use Kibana from server (DigitalOcean)?

### ISSUE THREAD

**Issue by SeppanenP** [jisosomppi/log-analysis#6]
If Master is a droplet in DigitalOcean, how can I use Kibana from there?

**Comment by jisosomppi** [comment]
If your minions have been set up correctly (connected to the master), their `/etc/hosts` file should contain the IP address of the master mapped to `logserver.local`. If this is not the case, try browsing directly to the droplets IP address or address:5601.

**Comment by jisosomppi** [comment]
You can also verify Kibana functionality by running `curl localhost` on the droplet via SSH.

**Comment by SeppanenP** [comment]
> If your minions have been set up correctly (connected to the master), their `/etc/hosts` file should contain the IP address of the master mapped to `logserver.local`. If this is not the case, try browsing directly to the droplets IP address or address:5601.
